image: gitpod/workspace-python-3.12

# Commands that will run on workspace start
tasks:
    - name: Build & watch docs
      before: pip install -r requirements.txt
      # init: sphinx-build -a -E -v -b html docs docs/_build/html
      # Use sphinx-autobuild to build the docs with each change, 
      # but we can not use it to server the docs, as it starts
      # a websocket-connection, which does not work via the gitpod forwarind
      command: sphinx-autobuild --port 8010 docs docs/_build/html 
    
    - name: Serve docs
      # Use a standard http-server to provide the docs.
      # User must realod the page with each change by hand!
      command: python -m http.server 8000 -d docs/_build/html
    - name: preview the web app
      command: |
          # wait for the port, and then browse a specific path
          gp ports await 8000 && gp preview $(gp url 8000)

# Ports to expose on workspace startup
# Docs:https://www.gitpod.io/docs/configure/workspaces/ports
ports:
    - port: 8000
      onOpen: ignore
      name: Sphinx-Demo docs
      description: Sphinx-Demo docs
      visibility: private

vscode:
  extensions:
    - trond-snekvik.simple-rst
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/useblocks/vsextensions/sphinx-needs-vscode/0.3.1/vspackage