image: gitpod/workspace-python-3.12

# Commands that will run on workspace start
tasks:
    - name: Build & deploy docs
      before: pip install -r requirements.txt
      init: sphinx-build -a -E -v -b html docs docs/_build/html
      command: python -m http.server 8000 -d docs/_build/html
    - name: preview the web app
      command: |
          # wait for the port, and then browse a specific path
          gp ports await 8000 && gp preview $(gp url 8000)

# Ports to expose on workspace startup
# Docs:https://www.gitpod.io/docs/configure/workspaces/ports
ports:
    - port: 8000
      onOpen: ignore
      name: Sphinx-Demo docs
      description: Sphinx-Demo docs
      visibility: private
