image:
    file: .gitpod.Dockerfile
# Commands that will run on workspace start
tasks:
    - name: 1) Build & watch docs
      # Use sphinx-autobuild to build the docs with each change,
      # but we can not use it to server the docs, as it starts
      # a websocket-connection, which does not work via the gitpod forwarind
      command: sphinx-autobuild --port 8010 docs docs/_build/html

    - name: 2) Serve docs
      # Use a standard http-server to provide the docs.
      # User must reload the page with each change by hand!
      command: python -m http.server 8000 -d docs/_build/html
    - name: 3) Preview the docs
      # We wait till sphinx-autobuild has finished on port 8010,
      # then we start the http-server on port 8000 and show it.
      command: |
          # wait for the port, and then browse a specific path
          gp ports await 8010 && gp preview $(gp url 8000)

# Ports to expose on workspace startup
# Docs:https://www.gitpod.io/docs/configure/workspaces/ports
ports:
    - port: 8000
      onOpen: ignore
      name: Sphinx-Demo docs
      description: Sphinx-Demo docs
      visibility: public
    - port: 8010
      onOpen: ignore
      name: Sphinx-Demo Autobuilder (not needed!)
      description: DO NOT USE - Port of Sphinx-Autobuilder extension, which does not work with gitpod proxy
      visibility: private

vscode:
  extensions:
    - trond-snekvik.simple-rst
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/useblocks/vsextensions/sphinx-needs-vscode/0.3.1/vspackage
