name: CI
on:
  pull_request:
jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Build docs
        run: uv run sphinx-build -W -b html . _build/html
        working-directory: docs
  ubc:
    name: ubc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: useblocks/ubc-action@0.1
        with:
          working-directory: docs
      - name: Run 'ubc check .'
        run: ubc check .