name: CI
on:
  pull_request:
jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install graphviz
        run: sudo apt-get install -y graphviz
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Build all demo projects
        run: scripts/build_docs.sh
      - name: Build ubtrace (automotive-adas)
        run: uv run sphinx-build -W -b ubtrace -D needs_variant_data_file=variants/eu_left.json . _build/ubtrace
        working-directory: docs/automotive-adas
  ubc:
    name: ubc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: useblocks/ubc-action@0.1
        with:
          version: "0.31.0b1"
          working-directory: docs
      - name: Run 'ubc check docs/ with variant'
        run: ubc check -c "needs.variant_data_file='docs/automotive-adas/variants/eu_left.json'" docs/
